# Generated by Django 5.2.1 on 2025-05-27 15:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_listings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodlisting',
            name='provider',
            field=models.ForeignKey(limit_choices_to={'user_type': 'Business'}, on_delete=django.db.models.deletion.CASCADE, related_name='food_listings', to=settings.AUTH_USER_MODEL),
        ),
    ]
