# Generated by Django 5.2.1 on 2025-05-25 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food_listings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='provider',
        ),
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='listing',
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
