# Generated by Django 5.2.3 on 2025-06-25 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("scheduling", "0001_initial"),
    ]

    operations = []
