# Generated by Django 5.2.3 on 2025-09-04 07:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scheduling", "0001_initial"),
    ]

    operations = [
        # First, remove the unique_together constraint before deleting fields
        migrations.AlterUniqueTogether(
            name="pickuptimeslot",
            unique_together=set(),
        ),
        
        # Now remove the foreign key field
        migrations.RemoveField(
            model_name="pickuptimeslot",
            name="pickup_schedule",
        ),
        migrations.RemoveField(
            model_name="pickupoptimization",
            name="business",
        ),
        migrations.RemoveField(
            model_name="scheduledpickup",
            name="time_slot",
        ),
        migrations.RemoveField(
            model_name="pickupanalytics",
            name="average_pickup_duration",
        ),
        migrations.RemoveField(
            model_name="pickupanalytics",
            name="efficiency_score",
        ),
        migrations.RemoveField(
            model_name="pickupanalytics",
            name="on_time_percentage",
        ),
        migrations.RemoveField(
            model_name="pickupanalytics",
            name="peak_hour_efficiency",
        ),
        migrations.RemoveField(
            model_name="pickupanalytics",
            name="slot_utilization_rate",
        ),
        migrations.RemoveField(
            model_name="pickupanalytics",
            name="total_cancelled",
        ),
        migrations.RemoveField(
            model_name="pickupanalytics",
            name="total_completed",
        ),
        migrations.RemoveField(
            model_name="pickupanalytics",
            name="total_missed",
        ),
        migrations.RemoveField(
            model_name="pickupanalytics",
            name="total_scheduled",
        ),
        migrations.RemoveField(
            model_name="scheduledpickup",
            name="food_listing",
        ),
        migrations.RemoveField(
            model_name="scheduledpickup",
            name="scheduled_date",
        ),
        migrations.RemoveField(
            model_name="scheduledpickup",
            name="scheduled_end_time",
        ),
        migrations.RemoveField(
            model_name="scheduledpickup",
            name="scheduled_start_time",
        ),
        migrations.AddField(
            model_name="pickupanalytics",
            name="average_preparation_time",
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="pickupanalytics",
            name="on_time_pickup_percentage",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="pickupanalytics",
            name="orders_cancelled",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="pickupanalytics",
            name="orders_completed",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="pickupanalytics",
            name="orders_missed",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="pickupanalytics",
            name="orders_ready",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="pickupanalytics",
            name="total_orders",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="scheduledpickup",
            name="actual_ready_time",
            field=models.DateTimeField(
                blank=True, help_text="When business marked order as ready", null=True
            ),
        ),
        migrations.AddField(
            model_name="scheduledpickup",
            name="estimated_ready_time",
            field=models.TimeField(
                blank=True,
                help_text="Estimated time when order will be ready",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="scheduledpickup",
            name="pickup_date",
            field=models.DateField(default=datetime.date(2025, 9, 4)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="scheduledpickup",
            name="pickup_deadline",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 9, 4, 7, 10, 58, 570685, tzinfo=datetime.timezone.utc
                ),
                help_text="Deadline for pickup (usually business closing time)",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="scheduledpickup",
            name="ready_notification_sent",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="scheduledpickup",
            name="ready_notification_sent_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="scheduledpickup",
            name="reminder_sent_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="scheduledpickup",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending Preparation"),
                    ("ready", "Ready for Pickup"),
                    ("completed", "Completed"),
                    ("missed", "Missed"),
                    ("cancelled", "Cancelled"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        
        # Delete the models after all field modifications
        migrations.DeleteModel(
            name="FoodListingPickupSchedule",
        ),
        migrations.DeleteModel(
            name="PickupOptimization",
        ),
        migrations.DeleteModel(
            name="PickupTimeSlot",
        ),
    ]