server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  # CI/CD workflow logs (if stored locally)
  - job_name: cicd_logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: cicd
          __path__: /var/log/cicd/*.log

  # Backend application logs
  - job_name: backend_logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: backend
          app: save-n-bite-backend
          __path__: /var/log/savenbite/backend/*.log

  # Frontend application logs
  - job_name: frontend_logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: frontend
          app: save-n-bite-frontend
          __path__: /var/log/savenbite/frontend/*.log

  # System logs
  - job_name: system
    static_configs:
      - targets:
          - localhost
        labels:
          job: varlogs
          __path__: /var/log/*log

  # Docker container logs
  - job_name: docker
    static_configs:
      - targets:
          - localhost
        labels:
          job: docker
          __path__: /var/lib/docker/containers/*/*.log
