# Generated by Django 5.2.3 on 2025-10-16 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_alter_notification_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('new_listing', 'New Listing'), ('listing_expiring', 'Listing Expiring'), ('business_update', 'Business Update'), ('system_announcement', 'System Announcement'), ('welcome', 'Welcome'), ('pickup_reminder', 'Pickup Reminder'), ('order_preparation', 'Order Preparation'), ('order_completion', 'Order Completion'), ('donation_request', 'Donation Request'), ('donation_response', 'Donation Response'), ('plant_earned', 'Plant Earned'), ('garden_milestone', 'Garden Milestone'), ('plant_collection_reward', 'Plant Collection Reward')], max_length=40),
        ),
    ]
