# Generated by Django 5.2.1 on 2025-05-27 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='country',
            field=models.CharField(default='South Africa', max_length=100),
        ),
        migrations.AddField(
            model_name='business',
            name='postal_code',
            field=models.CharField(default='0000', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='business',
            name='province_or_state',
            field=models.CharField(default='Gauteng', max_length=100),
            preserve_default=False,
        ),
    ]
