# Generated by Django 5.2.1 on 2025-05-25 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('normal', 'Normal User'), ('admin', 'Administrator')], default='normal', max_length=10),
        ),
    ]
