# Generated by Django 5.2.1 on 2025-05-27 12:13

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_business_country_business_postal_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='BusinessID',
            field=models.UUIDField(db_column='BusinessID', default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.RenameField(
            model_name='business',
            old_name='BusinessID',
            new_name='id',
        ),
        migrations.AlterField(
            model_name='individual',
            name='IndividualID',
            field=models.UUIDField(db_column='IndividualID', default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.RenameField(
            model_name='individual',
            old_name='IndividualID',
            new_name='id',
        ),
        migrations.AlterField(
            model_name='organisation',
            name='OrganisationID',
            field=models.UUIDField(db_column='OrganisationID', default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.RenameField(
            model_name='organisation',
            old_name='OrganisationID',
            new_name='id',
        ),
        migrations.AlterField(
            model_name='user',
            name='UserID',
            field=models.UUIDField(db_column='UserID', default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.RenameField(
            model_name='user',
            old_name='UserID',
            new_name='id',
        ),
    ]
