# Generated by Django 5.2.3 on 2025-07-12 04:51

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='interaction',
            name='motivation_message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='interaction',
            name='rejection_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='interaction',
            name='verification_documents',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.URLField(), blank=True, default=list, size=None),
        ),
        migrations.AlterField(
            model_name='interaction',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('ready', 'Ready for Pickup'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('failed', 'Failed'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
    ]
