# Generated by Django 5.2.3 on 2025-07-17 07:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0003_checkoutsession_delete_pickupdetails_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='cart',
            index=models.Index(fields=['expires_at'], name='interaction_expires_447294_idx'),
        ),
    ]
