# Generated by Django 5.2.3 on 2025-08-09 11:57

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0004_cart_expires_at_cart_interaction_expires_447294_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkoutsession',
            name='session_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique session identifier', unique=True),
        ),
    ]
