# Generated by Django 5.2.3 on 2025-08-09 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0005_checkoutsession_session_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='interactionstatushistory',
            old_name='Interaction',
            new_name='interaction',
        ),
    ]
