# Generated by Django 5.2.3 on 2025-09-12 11:09

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        (
            "interactions",
            "0006_rename_interaction_interactionstatushistory_interaction",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomerGarden",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(default="My Garden", max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("total_plants_earned", models.PositiveIntegerField(default=0)),
                ("total_plants_placed", models.PositiveIntegerField(default=0)),
                ("garden_level", models.PositiveIntegerField(default=1)),
                (
                    "customer",
                    models.OneToOneField(
                        limit_choices_to={"user_type": "customer"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="digital_garden",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Plant",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("scientific_name", models.CharField(blank=True, max_length=255)),
                (
                    "common_names",
                    models.JSONField(
                        default=list, help_text="Alternative common names"
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("vegetable", "Vegetable"),
                            ("succulent", "Succulent"),
                            ("flowering", "Flowering Plant"),
                            ("herb", "Herb"),
                            ("shrub", "Shrub"),
                            ("tree", "Tree"),
                            ("grass", "Grass"),
                            ("fern", "Fern"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "rarity",
                    models.CharField(
                        choices=[
                            ("common", "Common"),
                            ("uncommon", "Uncommon"),
                            ("rare", "Rare"),
                            ("epic", "Epic"),
                            ("legendary", "Legendary"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "native_region",
                    models.CharField(default="South Africa", max_length=255),
                ),
                (
                    "care_difficulty",
                    models.CharField(
                        choices=[
                            ("easy", "Easy"),
                            ("moderate", "Moderate"),
                            ("difficult", "Difficult"),
                        ],
                        default="easy",
                        max_length=20,
                    ),
                ),
                (
                    "sunlight_requirements",
                    models.CharField(
                        choices=[
                            ("full_sun", "Full Sun"),
                            ("partial_sun", "Partial Sun"),
                            ("shade", "Shade"),
                            ("any", "Any"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "water_requirements",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("moderate", "Moderate"),
                            ("high", "High"),
                        ],
                        max_length=50,
                    ),
                ),
                ("description", models.TextField()),
                (
                    "fun_facts",
                    models.TextField(help_text="Interesting facts about the plant"),
                ),
                (
                    "growing_tips",
                    models.TextField(help_text="Tips for growing at home"),
                ),
                (
                    "rive_asset_name",
                    models.CharField(
                        help_text="Name of Rive asset/animation", max_length=100
                    ),
                ),
                (
                    "icon_color",
                    models.CharField(
                        default="#62BD38",
                        help_text="Hex color for plant icon",
                        max_length=7,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name"],
                "indexes": [
                    models.Index(
                        fields=["rarity", "category"],
                        name="digital_gar_rarity_9379de_idx",
                    ),
                    models.Index(
                        fields=["is_active"], name="digital_gar_is_acti_8d1bf6_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="CustomerStats",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("total_orders", models.PositiveIntegerField(default=0)),
                (
                    "total_order_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "unique_businesses_ordered_from",
                    models.PositiveIntegerField(default=0),
                ),
                (
                    "achieved_milestones",
                    models.JSONField(
                        default=dict,
                        help_text="Track achieved milestones to prevent duplicate rewards",
                    ),
                ),
                ("last_calculated_at", models.DateTimeField(auto_now=True)),
                (
                    "customer",
                    models.OneToOneField(
                        limit_choices_to={"user_type": "customer"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="garden_stats",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["total_orders"], name="digital_gar_total_o_838d02_idx"
                    ),
                    models.Index(
                        fields=["total_order_amount"],
                        name="digital_gar_total_o_1d2ce5_idx",
                    ),
                    models.Index(
                        fields=["unique_businesses_ordered_from"],
                        name="digital_gar_unique__74ce59_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="GardenTile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "row",
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(7),
                        ]
                    ),
                ),
                (
                    "col",
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(7),
                        ]
                    ),
                ),
                ("planted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "custom_data",
                    models.JSONField(
                        default=dict,
                        help_text="Custom plant instance data (growth stage, color variants, etc.)",
                    ),
                ),
                (
                    "garden",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="garden_tiles",
                        to="digital_garden.customergarden",
                    ),
                ),
                (
                    "plant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="placed_tiles",
                        to="digital_garden.plant",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["garden", "row", "col"],
                        name="digital_gar_garden__065132_idx",
                    ),
                    models.Index(
                        fields=["plant"], name="digital_gar_plant_i_fbc3a1_idx"
                    ),
                ],
                "unique_together": {("garden", "row", "col")},
            },
        ),
        migrations.CreateModel(
            name="PlantInventory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("quantity", models.PositiveIntegerField(default=1)),
                (
                    "earned_reason",
                    models.CharField(
                        choices=[
                            ("order", "Regular Order"),
                            ("milestone_orders", "Order Count Milestone"),
                            ("milestone_amount", "Order Amount Milestone"),
                            ("milestone_businesses", "Business Diversity Milestone"),
                            ("special_event", "Special Event"),
                            ("admin_grant", "Admin Granted"),
                        ],
                        max_length=100,
                    ),
                ),
                ("earned_at", models.DateTimeField(auto_now_add=True)),
                (
                    "customer",
                    models.ForeignKey(
                        limit_choices_to={"user_type": "customer"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="plant_inventory",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "earned_from_order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="earned_plants",
                        to="interactions.order",
                    ),
                ),
                (
                    "plant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="digital_garden.plant",
                    ),
                ),
            ],
            options={
                "ordering": ["-earned_at"],
                "indexes": [
                    models.Index(
                        fields=["customer", "plant"],
                        name="digital_gar_custome_665733_idx",
                    ),
                    models.Index(
                        fields=["earned_reason"], name="digital_gar_earned__8eff3c_idx"
                    ),
                ],
                "unique_together": {("customer", "plant")},
            },
        ),
        migrations.CreateModel(
            name="PlantReward",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "milestone_type",
                    models.CharField(
                        choices=[
                            ("order_count", "Order Count Milestone"),
                            ("order_amount", "Order Amount Milestone"),
                            ("business_count", "Unique Business Count Milestone"),
                        ],
                        max_length=50,
                    ),
                ),
                ("milestone_value", models.PositiveIntegerField()),
                ("quantity", models.PositiveIntegerField(default=1)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "plant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="digital_garden.plant",
                    ),
                ),
            ],
            options={
                "ordering": ["milestone_type", "milestone_value"],
                "indexes": [
                    models.Index(
                        fields=["milestone_type", "is_active"],
                        name="digital_gar_milesto_428330_idx",
                    ),
                    models.Index(
                        fields=["milestone_value"],
                        name="digital_gar_milesto_3c836f_idx",
                    ),
                ],
                "unique_together": {("milestone_type", "milestone_value", "plant")},
            },
        ),
    ]
