# Generated by Django 5.2.3 on 2025-09-20 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("digital_garden", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="plant",
            name="svg_image_url",
            field=models.CharField(
                blank=True,
                help_text="URL path to SVG image (e.g., 'plants/basil.svg')",
                max_length=200,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="plant",
            name="care_difficulty",
            field=models.CharField(
                choices=[
                    ("easy", "Easy"),
                    ("moderate", "Moderate"),
                    ("difficult", "Difficult"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="plant",
            name="category",
            field=models.CharField(
                choices=[
                    ("herb", "Herb"),
                    ("vegetable", "Vegetable"),
                    ("flower", "Flower"),
                    ("fruit", "Fruit"),
                    ("succulent", "Succulent"),
                    ("tree", "Tree"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="plant",
            name="common_names",
            field=models.JSONField(default=list, help_text="List of common names"),
        ),
        migrations.AlterField(
            model_name="plant",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="plant",
            name="native_region",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="plant",
            name="rarity",
            field=models.CharField(
                choices=[
                    ("common", "Common"),
                    ("uncommon", "Uncommon"),
                    ("rare", "Rare"),
                    ("epic", "Epic"),
                    ("legendary", "Legendary"),
                ],
                default="common",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="plant",
            name="rive_asset_name",
            field=models.CharField(
                blank=True,
                help_text="Legacy field - now used for SVG image filename",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="plant",
            name="scientific_name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="plant",
            name="sunlight_requirements",
            field=models.CharField(
                choices=[
                    ("full_sun", "Full Sun"),
                    ("partial_sun", "Partial Sun"),
                    ("shade", "Shade"),
                    ("any", "Any"),
                ],
                max_length=20,
            ),
        ),
    ]
