global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'savenbite-cicd-monitor'
    environment: 'production'

# Alertmanager configuration (optional)
# alerting:
#   alertmanagers:
#     - static_configs:
#         - targets:
#           - alertmanager:9093

# Load rules once and periodically evaluate them
rule_files:
  - "/etc/prometheus/rules/*.yml"

scrape_configs:
  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
        labels:
          service: 'prometheus'

  # Pushgateway for CI/CD metrics
  - job_name: 'pushgateway'
    honor_labels: true
    static_configs:
      - targets: ['pushgateway:9091']
        labels:
          service: 'pushgateway'

  # Node Exporter for system metrics
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
        labels:
          service: 'node-exporter'

  # GitHub Actions CI/CD Metrics
  - job_name: 'github_actions_cicd'
    honor_labels: true
    scrape_interval: 30s
    static_configs:
      - targets: ['pushgateway:9091']
        labels:
          job: 'github_actions'
          project: 'save-n-bite'

  # Backend Services (if running locally)
  - job_name: 'backend'
    static_configs:
      - targets: ['host.docker.internal:8000']
        labels:
          service: 'django-backend'

  # Frontend Services (if running locally)
  - job_name: 'frontend'
    static_configs:
      - targets: ['host.docker.internal:3001']
        labels:
          service: 'react-frontend'
