# Generated by Django 5.2.3 on 2025-06-24 19:41

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodListing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('food_type', models.CharField(choices=[('ready_to_eat', 'Ready to Eat'), ('ingredients', 'Ingredients'), ('baked_goods', 'Baked Goods')], max_length=20)),
                ('original_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discounted_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.PositiveIntegerField()),
                ('quantity_available', models.PositiveIntegerField()),
                ('expiry_date', models.DateField()),
                ('pickup_window', models.CharField(max_length=50)),
                ('images', models.JSONField(blank=True, default=list)),
                ('allergens', models.JSONField(blank=True, default=list)),
                ('dietary_info', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('active', 'Active'), ('sold_out', 'Sold Out'), ('expired', 'Expired'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.ForeignKey(limit_choices_to={'user_type': 'provider'}, on_delete=django.db.models.deletion.CASCADE, related_name='food_listings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['food_type'], name='food_listin_food_ty_288f00_idx'), models.Index(fields=['status'], name='food_listin_status_d4fb72_idx'), models.Index(fields=['expiry_date'], name='food_listin_expiry__40b2c7_idx'), models.Index(fields=['created_at'], name='food_listin_created_d342ce_idx')],
            },
        ),
    ]
