# Generated by Django 5.2.3 on 2025-07-10 09:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_listings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='foodlisting',
            name='admin_flagged',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='foodlisting',
            name='admin_removal_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='foodlisting',
            name='removed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='foodlisting',
            name='removed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='removed_listings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='foodlisting',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('sold_out', 'Sold Out'), ('expired', 'Expired'), ('inactive', 'Inactive'), ('removed', 'Removed'), ('flagged', 'Flagged')], default='active', max_length=20),
        ),
    ]
