# Generated by Django 5.2.3 on 2025-07-17 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0002_user_account_locked_until_user_admin_notes_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="foodproviderprofile",
            name="business_hours",
            field=models.CharField(
                blank=True, help_text="e.g., 'Mon-Fri: 9AM-6PM'", max_length=255
            ),
        ),
        migrations.AddField(
            model_name="foodproviderprofile",
            name="geocoded_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="foodproviderprofile",
            name="geocoding_error",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="foodproviderprofile",
            name="geocoding_failed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="foodproviderprofile",
            name="latitude",
            field=models.DecimalField(
                blank=True, decimal_places=8, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="foodproviderprofile",
            name="longitude",
            field=models.DecimalField(
                blank=True, decimal_places=8, max_digits=11, null=True
            ),
        ),
        migrations.AddField(
            model_name="foodproviderprofile",
            name="phone_number",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="foodproviderprofile",
            name="website",
            field=models.URLField(blank=True),
        ),
    ]
