# Generated by Django 5.2.4 on 2025-08-08 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_foodproviderprofile_business_hours_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodproviderprofile',
            name='banner',
            field=models.ImageField(blank=True, help_text='Banner image for business profile page (recommended size: 1200x400px)', null=True, upload_to='provider_banners/'),
        ),
        migrations.AddField(
            model_name='foodproviderprofile',
            name='banner_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='foodproviderprofile',
            name='business_description',
            field=models.TextField(blank=True, help_text='Tell customers about your business, cuisine, values, or specialties', max_length=1000),
        ),
        migrations.AddField(
            model_name='foodproviderprofile',
            name='business_tags',
            field=models.JSONField(blank=True, default=list, help_text="Custom tags to describe your business (e.g., ['Bakery', 'Vegan Options', 'Organic'])"),
        ),
        migrations.AddField(
            model_name='foodproviderprofile',
            name='description_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='foodproviderprofile',
            name='tags_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
