# Generated by Django 5.2.3 on 2025-08-13 10:21

import blob_storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0004_foodproviderprofile_banner_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customerprofile",
            name="profile_image",
            field=models.ImageField(
                blank=True,
                help_text="Profile image (max 5MB)",
                null=True,
                storage=blob_storage.get_customer_profile_storage,
                upload_to=blob_storage.customer_profile_image_path,
            ),
        ),
        migrations.AlterField(
            model_name="foodproviderprofile",
            name="banner",
            field=models.ImageField(
                blank=True,
                help_text="Banner image for business profile page (recommended size: 1200x400px, max 5MB)",
                null=True,
                storage=blob_storage.get_provider_banner_storage,
                upload_to=blob_storage.provider_banner_path,
            ),
        ),
        migrations.AlterField(
            model_name="foodproviderprofile",
            name="cipc_document",
            field=models.FileField(
                help_text="CIPC registration document (PDF, max 10MB)",
                storage=blob_storage.get_provider_document_storage,
                upload_to=blob_storage.provider_cipc_path,
            ),
        ),
        migrations.AlterField(
            model_name="foodproviderprofile",
            name="logo",
            field=models.ImageField(
                blank=True,
                help_text="Business logo (max 5MB)",
                null=True,
                storage=blob_storage.get_provider_logo_storage,
                upload_to=blob_storage.provider_logo_path,
            ),
        ),
        migrations.AlterField(
            model_name="ngoprofile",
            name="npo_document",
            field=models.FileField(
                help_text="NPO registration document (PDF, max 10MB)",
                storage=blob_storage.get_ngo_document_storage,
                upload_to=blob_storage.ngo_document_path,
            ),
        ),
        migrations.AlterField(
            model_name="ngoprofile",
            name="organisation_logo",
            field=models.ImageField(
                blank=True,
                help_text="Organisation logo (max 5MB)",
                null=True,
                storage=blob_storage.get_ngo_logo_storage,
                upload_to=blob_storage.ngo_logo_path,
            ),
        ),
    ]
