# Generated by Django 5.2.3 on 2025-07-09 10:50

import django.contrib.postgres.fields
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminActionLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action_type', models.CharField(choices=[('user_verification', 'User Verification'), ('user_management', 'User Management'), ('listing_moderation', 'Listing Moderation'), ('system_announcement', 'System Announcement'), ('password_reset', 'Password Reset'), ('data_export', 'Data Export')], max_length=30)),
                ('target_type', models.CharField(max_length=50)),
                ('target_id', models.CharField(max_length=100)),
                ('action_description', models.TextField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('admin_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_actions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['admin_user', 'timestamp'], name='admin_syste_admin_u_c09dbd_idx'), models.Index(fields=['action_type', 'timestamp'], name='admin_syste_action__e757f1_idx'), models.Index(fields=['target_type', 'target_id'], name='admin_syste_target__bb5d0b_idx')],
            },
        ),
        migrations.CreateModel(
            name='DocumentAccessLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_type', models.CharField(max_length=50)),
                ('profile_type', models.CharField(max_length=20)),
                ('profile_id', models.CharField(max_length=100)),
                ('document_name', models.CharField(max_length=255)),
                ('access_timestamp', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('admin_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_accesses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-access_timestamp'],
                'indexes': [models.Index(fields=['admin_user', 'access_timestamp'], name='admin_syste_admin_u_a0b70d_idx'), models.Index(fields=['profile_type', 'profile_id'], name='admin_syste_profile_c39fdb_idx')],
            },
        ),
        migrations.CreateModel(
            name='PasswordReset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('temporary_password_hash', models.CharField(max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('is_expired', models.BooleanField(default=False)),
                ('reset_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='initiated_resets', to=settings.AUTH_USER_MODEL)),
                ('target_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_password_resets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['target_user', 'created_at'], name='admin_syste_target__581fe3_idx'), models.Index(fields=['expires_at', 'is_expired'], name='admin_syste_expires_fea3f5_idx')],
            },
        ),
        migrations.CreateModel(
            name='SystemAnnouncement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=10)),
                ('target_user_types', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), default=list, help_text='User types to target: customer, provider, ngo', size=None)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['is_active', 'created_at'], name='admin_syste_is_acti_44f02f_idx'), models.Index(fields=['priority', 'created_at'], name='admin_syste_priorit_b71c5a_idx')],
            },
        ),
        migrations.CreateModel(
            name='SystemLogEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('error', 'Error'), ('critical', 'Critical')], max_length=10)),
                ('category', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('error_details', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('open', 'Open'), ('investigating', 'Investigating'), ('resolved', 'Resolved'), ('ignored', 'Ignored')], default='open', max_length=15)),
                ('resolution_notes', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['severity', 'timestamp'], name='admin_syste_severit_a05224_idx'), models.Index(fields=['status', 'timestamp'], name='admin_syste_status_95ac04_idx'), models.Index(fields=['category', 'timestamp'], name='admin_syste_categor_ca4109_idx')],
            },
        ),
    ]
