# Generated by Django 5.2.3 on 2025-09-07 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_system', '0002_add_access_log'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='accesslog',
            new_name='admin_syste_timesta_37fe35_idx',
            old_name='admin_syste_timesta_b82f42_idx',
        ),
        migrations.RenameIndex(
            model_name='accesslog',
            new_name='admin_syste_user_id_614488_idx',
            old_name='admin_syste_user_id_0f8e98_idx',
        ),
        migrations.RenameIndex(
            model_name='accesslog',
            new_name='admin_syste_ip_addr_d8caef_idx',
            old_name='admin_syste_ip_addr_e7c4d0_idx',
        ),
        migrations.RenameIndex(
            model_name='accesslog',
            new_name='admin_syste_status__8c1a16_idx',
            old_name='admin_syste_status__a91b55_idx',
        ),
    ]
