# .github/workflows/build-only.yml
name: Build and Push Images
on:
  push:
    branches: [ dev ]
  workflow_dispatch:

env:
  REGISTRY: savenbiteregistry-c0bnbkfndeayfbae.azurecr.io
  BACKEND_IMAGE: savenbite-backend
  FRONTEND_IMAGE: savenbite-frontend
  REACT_APP_API_URL: https://savenbiteservice-hzghg8gcgddtcfg7.southafricanorth-01.azurewebsites.net

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Log environment variables
      run: |
        echo "Building with API URL: ${{ env.REACT_APP_API_URL }}"
        echo "Registry: ${{ env.REGISTRY }}"
        
    - name: Log in to Azure Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}
        
    - name: Build and push backend image
      uses: docker/build-push-action@v5
      with:
        context: ./save-n-bite-backend
        file: ./save-n-bite-backend/Dockerfile.prod
        push: true
        tags: ${{ env.REGISTRY }}/${{ env.BACKEND_IMAGE }}:${{ github.sha }},${{ env.REGISTRY }}/${{ env.BACKEND_IMAGE }}:latest
        
    - name: Build and push frontend image
      uses: docker/build-push-action@v5
      with:
        context: ./save-n-bite-frontend
        file: ./save-n-bite-frontend/Dockerfile.prod
        push: true
        tags: ${{ env.REGISTRY }}/${{ env.FRONTEND_IMAGE }}:${{ github.sha }},${{ env.REGISTRY }}/${{ env.FRONTEND_IMAGE }}:latest
        build-args: |
          REACT_APP_API_URL=${{ env.REACT_APP_API_URL }}
        # Add more verbose output
        outputs: type=registry,push=true
        
    - name: Verify images were pushed
      run: |
        echo "✅ Backend image: ${{ env.REGISTRY }}/${{ env.BACKEND_IMAGE }}:latest"
        echo "✅ Frontend image: ${{ env.REGISTRY }}/${{ env.FRONTEND_IMAGE }}:latest"
        echo "🔧 Frontend built with API URL: ${{ env.REACT_APP_API_URL }}"
