# .github/workflows/frontend-ci.yml
name: Frontend CI/CD Pipeline

on:
  push:
    branches: [ main, frontend ]
  pull_request:
    branches: [ main, frontend ]

env:
  NODE_VERSION: '20'

jobs:
  frontend-tests:
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: ./save-n-bite-frontend
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          cache-dependency-path: './save-n-bite-frontend/package-lock.json'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Run Vitest
        run: npm test
        
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          file: ./save-n-bite-frontend/coverage/coverage-final.json
          flags: frontend
