name: frontend
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
env:
  NODE_VERSION: 20
jobs:
  frontend-tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./save-n-bite-frontend
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{env.NODE_VERSION}}
          cache: 'npm'
          cache-dependency-path: './save-n-bite-frontend/package-lock.json'
      - name: Install Dependencies
        run: npm install
      - name: Run Tests with Coverage
        run: npm run test:coverage
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4
        with:
          directory: ./save-n-bite-frontend/coverage
          fail_ci_if_error: true
          token: ${{ secrets.CODECOV_TOKEN }}
      - name: Comment PR with Coverage
        if: github.event_name == 'pull_request'
        uses: romeovs/lcov-reporter-action@v0.3.1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          lcov-file: ./save-n-bite-frontend/coverage/lcov.info