# .github/workflows/ci-cd.yml
name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  PYTHON_VERSION: '3.12'
  NODE_VERSION: '20'

jobs:
  # Backend Tests (Django + Pytest)
  backend-tests:
    runs-on: ubuntu-latest
    
    # Set working directory for backend
    defaults:
      run:
        working-directory: ./save-n-bite-backend
    
    services:
      postgres:
        image: postgres:17
        env:
          POSTGRES_PASSWORD: ${{ secrets.DB_USER_PASSWORD }}
          POSTGRES_USER: ${{ secrets.DB_USER }}
          POSTGRES_DB: ${{ secrets.DB_NAME }}
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.PYTHON_VERSION }}
    
    - name: Cache pip dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest pytest-cov
    
    - name: Run Django migrations
      env:
        DB_NAME: ${{ secrets.DB_NAME }}
        DB_USER: ${{ secrets.DB_USER }}
        DB_USER_PASSWORD: ${{ secrets.DB_USER_PASSWORD }}
        DB_HOST: localhost
        DB_PORT: 5432
        SECRET_KEY: 'test-secret-key-for-ci'
        DEBUG: 'False'
        DJANGO_SETTINGS_MODULE: backend.settings
      run: |
        python manage.py migrate
    
    - name: Run Pytest
      env:
        DB_NAME: ${{ secrets.DB_NAME }}
        DB_USER: ${{ secrets.DB_USER }}
        DB_USER_PASSWORD: ${{ secrets.DB_USER_PASSWORD }}
        DB_HOST: localhost
        DB_PORT: 5432
        SECRET_KEY: 'test-secret-key-for-ci'
        DEBUG: 'False'
        DJANGO_SETTINGS_MODULE: backend.settings
      run: |
        pytest --cov=. --cov-report=xml --cov-report=html
    
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./save-n-bite-backend/coverage.xml
        flags: backend

  # Frontend Tests (React + Vitest)
  frontend-tests:
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: ./save-n-bite-frontend
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'
        cache-dependency-path: './save-n-bite-frontend/package-lock.json'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Run Vitest
      run: npm run test -- --run
    
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./save-n-bite-frontend/coverage/coverage-final.json
        flags: frontend
